# version: '3.8'

services:
  # Qdrant - Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: allyin_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped

  # Neo4j - Graph Database
  neo4j:
    image: neo4j:latest
    container_name: allyin_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    restart: unless-stopped

  # Optional: Neo4j Browser for visualization
  neo4j-browser:
    image: neo4j:latest
    container_name: allyin_neo4j_browser
    ports:
      - "7575:7474"
    environment:
      - NEO4J_AUTH=none
    command: neo4j-admin server console
    profiles:
      - debug

  # Optional: Qdrant Web UI
  qdrant-ui:
    image: qdrant/qdrant-web-ui:latest
    container_name: allyin_qdrant_ui
    ports:
      - "6335:80"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    profiles:
      - debug

# Networks
networks:
  default:
    name: allyin_network

# Volumes
volumes:
  qdrant_storage:
  neo4j_data:
  neo4j_logs:
